name: CI/CD for Next.js app to Azure Web App

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'Test'
        type: choice
        options:
          - Test
          - Production

env:
  NODE_VERSION: "20.x"

jobs:
  ci-check:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install & Build (CI)
        run: |
          npm install
          npm run build
        working-directory: ./dev-share-ui

  deploy:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    env:
      DEPLOY_ENV: ${{ github.event.inputs.environment || 'Test' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Copy correct .env file
        run: |
          envFile=".env.test"
          if [[ "${{ env.DEPLOY_ENV }}" == "Production" ]]; then
            envFile=".env.production"
          fi
          cp ./dev-share-ui/$envFile ./dev-share-ui/.env

      - name: Install & Build
        run: |
          npm install
          npm run build
        working-directory: ./dev-share-ui

      - name: Prepare static assets
        run: |
          cd dev-share-ui
          cp -r .next/static .next/standalone/.next/
          if [ -d "public" ]; then cp -r public .next/standalone/; fi

      - name: Deploy to Azure Web App - Production
        if: env.DEPLOY_ENV == 'Production'
        uses: azure/webapps-deploy@v3
        with:
          app-name: prod-share-ui
          publish-profile: ${{ secrets.PROD_APP_PUBLISH_PROFILE }}
          package: dev-share-ui/.next/standalone

      - name: Deploy to Azure Web App - Test
        if: env.DEPLOY_ENV != 'Production'
        uses: azure/webapps-deploy@v3
        with:
          app-name: dev-share-ui-v1
          publish-profile: ${{ secrets.APP_PUBLISH_PROFILE }}
          package: dev-share-ui/.next/standalone