name: Build and deploy .NET app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: '选择部署环境'
        required: true
        default: 'Test'
        type: choice
        options:
          - Test
          - Production

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    env:
      IS_PRODUCTION: ${{ github.event.inputs.environment == 'Production' }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ./dev-share-api/dev-share-api.csproj

      - name: Build
        run: dotnet build ./dev-share-api/dev-share-api.csproj --configuration Release --no-restore

      - name: Publish
        run: |
          dotnet publish ./dev-share-api/dev-share-api.csproj \
            --configuration Release \
            --output ./publish \
            -p:EnvironmentName=${{ env.IS_PRODUCTION == 'true' && 'Production' || 'Test' }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.IS_PRODUCTION == 'true' && 'prod-share-app' || 'dev-share' }}
          publish-profile: ${{ env.IS_PRODUCTION == 'true' && secrets.PROD_AZURE_WEBAPP_PUBLISH_PROFILE || secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish