name: CI/CD for .NET app to Azure

on:
  # ✅ PR 到 main：只执行 CI
  pull_request:
    branches: ['main']

  # ✅ 合并 PR 到 main：自动部署到 Test
  push:
    branches: ['main']

  # ✅ 手动触发部署
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'Test'
        type: choice
        options:
          - Test
          - Production

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  ci-check:
    # ✅ 只在 PR 阶段执行
    if: github.event_name == 'pull_request'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ./dev-share-api/dev-share-api.csproj

      - name: Build
        run: dotnet build ./dev-share-api/dev-share-api.csproj --configuration Release --no-restore

  deploy:
    # ✅ 仅在 main 合并 或 workflow_dispatch 时执行
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ./dev-share-api/dev-share-api.csproj

      - name: Build
        run: dotnet build ./dev-share-api/dev-share-api.csproj --configuration Release --no-restore

      - name: Publish
        run: |
          $envName = if ("${{ github.event.inputs.environment }}" -eq "Production") { "Production" } else { "Test" }
          dotnet publish ./dev-share-api/dev-share-api.csproj `
            --configuration Release `
            --output ./publish `
            -p:EnvironmentName=$envName

      - name: Deploy to Azure Web App - Production
        if: github.event.inputs.environment == 'Production'
        uses: azure/webapps-deploy@v3
        with:
          app-name: prod-share-app
          publish-profile: ${{ secrets.PROD_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

      - name: Deploy to Azure Web App - Test
        if: github.event.inputs.environment != 'Production'
        uses: azure/webapps-deploy@v3
        with:
          app-name: dev-share
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish