name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - '**'  
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.APP_PUBLISH_PROFILE }}
  WEBAPP_NAME: "dev-share-ui-v1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build
        working-directory: ./dev-share-ui

      - name: Copy static assets for standalone
        run: |
          cd dev-share-ui
          cp -r .next/static .next/standalone/.next/
          if [ -d "public" ]; then cp -r public .next/standalone/; fi

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package:  dev-share-ui/.next/standalone