name: CI/CD for .NET app to Azure

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'Test'
        type: choice
        options:
          - Test
          - Production

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  ci-check:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ./dev-share-api/dev-share-api.csproj

      - name: Build
        run: dotnet build ./dev-share-api/dev-share-api.csproj --configuration Release --no-restore

  deploy:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: windows-latest

    env:
      DEPLOY_ENV: ${{ github.event.inputs.environment || 'Test' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ./dev-share-api/dev-share-api.csproj

      - name: Build
        run: dotnet build ./dev-share-api/dev-share-api.csproj --configuration Release --no-restore

      - name: Publish
        run: |
          $envName = "${{ env.DEPLOY_ENV }}"
          dotnet publish ./dev-share-api/dev-share-api.csproj `
            --configuration Release `
            --output ./publish `
            -p:EnvironmentName=$envName

      - name: Deploy to Azure Web App - Production
        if: env.DEPLOY_ENV == 'Production'
        uses: azure/webapps-deploy@v3
        with:
          app-name: prod-share-app
          publish-profile: ${{ secrets.PROD_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

      - name: Deploy to Azure Web App - Test
        if: env.DEPLOY_ENV != 'Production'
        uses: azure/webapps-deploy@v3
        with:
          app-name: dev-share
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish