name: Build and deploy .NET app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: '选择部署环境'
        required: true
        default: 'Test'
        type: choice
        options:
          - Test
          - Production

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ./dev-share-api/dev-share-api.csproj

      - name: Build
        run: dotnet build ./dev-share-api/dev-share-api.csproj --configuration Release --no-restore

      - name: Publish
        run: |
          $envName = if ("${{ github.event.inputs.environment }}" -eq "Production") { "Production" } else { "Test" }
          dotnet publish ./dev-share-api/dev-share-api.csproj `
            --configuration Release `
            --output ./publish `
            -p:EnvironmentName=$envName

      - name: Deploy to Azure Web App - Production
        if: ${{ github.event.inputs.environment == 'Production' }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: prod-share-app
          publish-profile: ${{ secrets.PROD_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

      - name: Deploy to Azure Web App - Test
        if: ${{ github.event.inputs.environment == 'Test' }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: dev-share
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish