name: CI/CD for Next.js app to Azure Web App

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'Test'
        type: choice
        options:
          - Test
          - Production
  push:
    branches:
      - main

env:
  NODE_VERSION: "20.x"

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Only deploy on manual trigger or main push
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Copy correct .env file
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "Production" ]]; then
            cp ./dev-share-ui/.env.production ./dev-share-ui/.env
          else
            cp ./dev-share-ui/.env.test ./dev-share-ui/.env
          fi

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
        working-directory: ./dev-share-ui

      - name: Prepare static assets for standalone deployment
        run: |
          cd dev-share-ui
          cp -r .next/static .next/standalone/.next/
          if [ -d "public" ]; then cp -r public .next/standalone/; fi

      - name: Deploy to Azure Web App - Production
        if: ${{ github.event.inputs.environment == 'Production' }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: prod-share-ui
          publish-profile: ${{ secrets.PROD_APP_PUBLISH_PROFILE }}
          package: dev-share-ui/.next/standalone

      - name: Deploy to Azure Web App - Test
        if: ${{ github.event.inputs.environment != 'Production' }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: dev-share-ui-v1
          publish-profile: ${{ secrets.APP_PUBLISH_PROFILE }}
          package: dev-share-ui/.next/standalone